from unittest.mock import MagicMock, patch

import jwt as pyjwt
import pytest
from cryptography.hazmat.primitives.asymmetric import rsa


@pytest.fixture(autouse=True)
def reset_key_manager_singleton():
    """Reset KeyManager singleton so each test gets fresh state."""
    from src.utils.key_manager import KeyManager

    KeyManager._instance = None
    yield
    KeyManager._instance = None


@pytest.fixture
def mock_key_manager():
    """Provide a KeyManager mock backed by a real RSA key pair."""
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()

    km = MagicMock()
    km.private_key = private_key
    km.public_key = public_key
    km.kid = "test-kid-123"
    return km


def test_generate_auth_token_returns_string(mock_key_manager):
    """generate_auth_token returns a non-empty JWT string."""
    with patch("src.utils.jwt_utils.KeyManager", return_value=mock_key_manager):
        from src.utils.jwt_utils import JWTUtils

        token = JWTUtils.generate_auth_token({"sub": "alice", "exp": 9999999999})

    assert isinstance(token, str)
    assert len(token) > 0


def test_generate_auth_token_sets_kid_header(mock_key_manager):
    """Generated token header contains kid and RS256 alg."""
    with patch("src.utils.jwt_utils.KeyManager", return_value=mock_key_manager):
        from src.utils.jwt_utils import JWTUtils

        token = JWTUtils.generate_auth_token({"sub": "alice", "exp": 9999999999})

    header = pyjwt.get_unverified_header(token)
    assert header["kid"] == "test-kid-123"
    assert header["alg"] == "RS256"
    assert header["typ"] == "JWT"


def test_decode_auth_token_roundtrip(mock_key_manager):
    """A token generated by generate_auth_token can be decoded by decode_auth_token."""
    with patch("src.utils.jwt_utils.KeyManager", return_value=mock_key_manager):
        from src.utils.jwt_utils import JWTUtils

        claims = {"sub": "alice", "exp": 9999999999}
        token = JWTUtils.generate_auth_token(claims)
        decoded = JWTUtils.decode_auth_token(token)

    assert decoded["sub"] == "alice"


def test_decode_auth_token_rejects_tampered_token(mock_key_manager):
    """decode_auth_token raises on a tampered token."""
    with patch("src.utils.jwt_utils.KeyManager", return_value=mock_key_manager):
        from src.utils.jwt_utils import JWTUtils

        token = JWTUtils.generate_auth_token({"sub": "alice", "exp": 9999999999})
        tampered_token = token[:-4] + "XXXX"

        with pytest.raises(pyjwt.InvalidTokenError):
            JWTUtils.decode_auth_token(tampered_token)


def test_decode_auth_token_rejects_wrong_key():
    """decode_auth_token raises when decoding with a different key pair."""
    key1 = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    key2 = rsa.generate_private_key(public_exponent=65537, key_size=2048)

    km_sign = MagicMock()
    km_sign.private_key = key1
    km_sign.kid = "kid-1"

    km_verify = MagicMock()
    km_verify.public_key = key2.public_key()

    with patch("src.utils.jwt_utils.KeyManager", return_value=km_sign):
        from src.utils.jwt_utils import JWTUtils

        token = JWTUtils.generate_auth_token({"sub": "alice", "exp": 9999999999})

    with (
        patch("src.utils.jwt_utils.KeyManager", return_value=km_verify),
        pytest.raises(pyjwt.InvalidTokenError),
    ):
        JWTUtils.decode_auth_token(token)
