apiVersion: v1
kind: Service
metadata:
  name: mysql-workbench
  namespace: tic-tac-toe
  labels:
    app: mysql-workbench
spec:
  selector:
    app: mysql-workbench
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: websocket
      port: 3001
      targetPort: 3001
  type: ClusterIP
