apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-workbench
  namespace: tic-tac-toe
  labels:
    app: mysql-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-workbench
  template:
    metadata:
      labels:
        app: mysql-workbench
    spec:
      containers:
        - name: mysql-workbench
          image: lspipepr/mysql-workbench:version-8.0.28
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tic-tac-toe-secrets
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 30
