include:
  - path:
      - ./components/auth_service_db/docker-compose.yaml
    env_file:
      - ./.env
  - path:
      - ./components/auth_service_app/docker-compose.yaml
    env_file:
      - ./.env

networks:
    auth-service-api-network:
        name: auth-service-api-network
    observability:
        external: true
        name: ${OBSERVABILITY_NETWORK_NAME}