apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: tic-tac-toe
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: tic-tac-toe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
