services:
  auth-service-database:
    image: mysql:8.0.29
    container_name: auth-service-database
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTH_SERVICE_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 5
    volumes:
      - auth-service-database_data:/var/lib/mysql
    networks:
      - auth-service-api-network
      - observability

  auth-service-liquibase:
    container_name: auth-service-liquibase
    build:
      context: ./migrations
      dockerfile: Dockerfile
      args:
        MYSQL_HOST: auth-service-database
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${AUTH_SERVICE_MYSQL_ROOT_PASSWORD}
        LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
    depends_on:
      auth-service-database:
        condition: service_healthy
    environment:
      MYSQL_HOST: auth-service-database
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_SERVICE_MYSQL_ROOT_PASSWORD}
      LIQUIBASE_LOG_LEVEL: ${LIQUIBASE_LOG_LEVEL}
    volumes:
      - ./migrations/changelog:/liquibase/changelog
    networks:
      - auth-service-api-network
      - observability

  auth-service-phpmyadmin:
    image: phpmyadmin:latest
    container_name: auth-service-phpmyadmin
    restart: always
    environment:
      PMA_HOST: auth-service-database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${AUTH_SERVICE_MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    depends_on:
      auth-service-database:
        condition: service_healthy
    networks:
      - auth-service-api-network

volumes:
  auth-service-database_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/database/mysql